#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# vi key binding
bindkey '^R' history-incremental-search-backward
bindkey -rM vicmd 'v'
bindkey -M vicmd '^v' edit-command-line

# reverse-menu-complete key binding
bindkey '^[[Z' reverse-menu-complete

# Alias
alias -g tmux2='tmux -2'    # tmux 256 color
alias -g vi='vim'           # vim
alias -g tiga='tig --all'   # tig all branches

# fasd
fasd_cache="$HOME/.fasd-init-zsh"
if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
  fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install >| "$fasd_cache"
fi
source "$fasd_cache"
unset fasd_cache

alias v='f -e vim'

# nvm
export NVM_DIR="/Users/nimo/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
